### ISSUE TITLE
Unable to find manifest file in dist

### ISSUE THREAD

**Issue by gidoichi** [thechrisjohnson/terraform-cloud-provider-publish#346]
## Problem

Using this action to publish my private provider to the HCP Terraform private registry results in the following errors, preventing the provider from being published.

```
▶ Run thechrisjohnson/terraform-cloud-provider-publish@74d9a5efff0ddecb096f4f91f0a1f4b05bf24d13
Error: Unable to find manifest file in /home/runner/work/myprovider/myprovider/dist
```

## Debugging

No *manifest.json file exists in the dist directory when using the find command.

```
./dist/myprovider_darwin_amd64_v1/myprovider_v0.0.1
./dist/myprovider_0.4.1_darwin_arm64.zip
./dist/myprovider_windows_arm64_v8.0/myprovider_v0.0.1.exe
./dist/myprovider_0.4.1_windows_arm64.zip
./dist/myprovider_windows_amd64_v1/myprovider_v0.0.1.exe
./dist/myprovider_linux_arm64_v8.0/myprovider_v0.0.1
./dist/myprovider_0.4.1_linux_amd64.zip
./dist/myprovider_0.4.1_darwin_amd64.zip
./dist/myprovider_0.4.1_linux_arm64.zip
./dist/myprovider_linux_amd64_v1/myprovider_v0.0.1
./dist/myprovider_0.4.1_freebsd_386.zip
./dist/myprovider_0.4.1_freebsd_arm.zip
./dist/myprovider_0.4.1_windows_386.zip
./dist/myprovider_0.4.1_SHA256SUMS
./dist/myprovider_freebsd_arm64_v8.0/myprovider_v0.0.1
./dist/myprovider_0.4.1_windows_amd64.zip
./dist/myprovider_windows_386_sse2/myprovider_v0.0.1.exe
./dist/myprovider_linux_arm_6/myprovider_v0.0.1
./dist/myprovider_0.4.1_freebsd_arm64.zip
./dist/myprovider_freebsd_amd64_v1/myprovider_v0.0.1
./dist/myprovider_0.4.1_windows_arm.zip
./dist/artifacts.json
./dist/myprovider_windows_arm_6/myprovider_v0.0.1.exe
./dist/myprovider_freebsd_386_sse2/myprovider_v0.0.1
./dist/myprovider_darwin_arm64_v8.0/myprovider_v0.0.1
./dist/myprovider_linux_386_sse2/myprovider_v0.0.1
./dist/metadata.json
./dist/config.yaml
./dist/myprovider_0.4.1_SHA256SUMS.sig
./dist/myprovider_0.4.1_linux_386.zip
./dist/myprovider_0.4.1_linux_arm.zip
./dist/myprovider_0.4.1_freebsd_amd64.zip
./dist/myprovider_freebsd_arm_6/myprovider_v0.0.1
```

According to the output of the `Run GoReleaser` step, metadata.json is useful for detecting [providerVersion](https://github.com/thechrisjohnson/terraform-cloud-provider-publish/blob/v1.5/src/main.ts#L49) instead.

```
▼ Metadata output
  {"project_name":"myprovider","tag":"v0.0.0","previous_tag":"v0.0.1","version":"0.0.0","commit":"ed7575b6d01ae6125790842a499ee0dfe070d0cc","date":"2025-03-09T09:42:53.045472688Z","runtime":{"goos":"linux","goarch":"amd64"}}
```

## Workaround

@kang8's solution worked for me.
- https://github.com/kang8/terraform-cloud-provider-publish/commit/200729485cae7c7d1b3dd9db523bd7771061d2fb

To use this, I specified the action and the commit hash.

```yaml
uses: kang8/terraform-cloud-provider-publish@76ae845700d8233eb3940250b11f80a18e8d4102
```

## Environment

The error occurred in the following workflow.

```yaml
# Terraform Provider release workflow.
name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - 'v*'

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          args: release --clean
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - name: Publish provider
        uses: thechrisjohnson/terraform-cloud-provider-publish@74d9a5efff0ddecb096f4f91f0a1f4b05bf24d13 # v1.5
        with:
            organization-name: ${{ vars.ORGANIZATION_NAME }}
            organization-api-token: ${{ secrets.TF_CLOUD_TOKEN }}
            provider-directory: dist
            gpg-key: ${{ secrets.GPG_PUBLIC_KEY }}
```
